// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlgen_todos

type Company struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NewUser struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Password string `json:"password"`
}

type User struct {
	ID       string   `json:"id"`
	Name     string   `json:"name"`
	Password string   `json:"password"`
	Company  *Company `json:"company"`
}
